title: Charles J. Wolock 
url: "https://cwolock.github.io"
baseurl: "https://cwolock.github.io"
description: "Charlie's website"

markdown: kramdown

tracking_id: #

footer: no 
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "CV"
   link: "cjw_cv.pdf"

